# Write a Python program to combine values in python list of dictionaries. Go to the
a= [{'item': 'item1', 'amount': 400}, {'item': 'item2', 'amount': 300},{'item': 'item1', 'amount': 750}]
# Expected Output: Counter({'item1': 1150, 'item2': 300})
n=0
while i<len(a):
    


















# ample string : 'w3resource'
# Expected output: {'w': 1, '3': 1, 'r': 2, 'e': 2, 's': 1, 'o': 1, 'u': 1, 'c': 1}
# string="w3resource"
# s=[]
# g={}
# for i in string:
#     s.append(i)
#     e=i.count(s)
#     g.update({s:e})
# print(g)
    
# n=int(input("enter:"))
# a=["A","B"]
# h=[]
# i=0
# while i<=n:
#     j=0
#     while j<len(a):



